name: Security-Scan

on:
  workflow_dispatch
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    paths:
      - src

jobs:
  action:
    name: Security Scan
    uses: Fortiwatch/advanced-security-compliance/.github/workflows/codeql-analysis.yml@main
    with:
      #config-file: ./.github/codeql-config.yml
      auto-build: false
      custom-build: ./gradlew build
      
      
