name: Security-Scan

on:
  workflow_dispatch

jobs:
  action:
    name: Security Scan
    uses: Fortiwatch/advanced-security-compliance/.github/workflows/codeql-analysis.yml@main
    with:
      auto-build: false
      custom-build: ./gradlew build
      config-file: ./.github/codeql-config.yml
      
